DROP TABLE THETEAMPROJECT.TRADERS CASCADE CONSTRAINTS;

CREATE TABLE THETEAMPROJECT.TRADERS (
  ID         NUMBER(*, 0),
  TRADERNAME VARCHAR2(255 BYTE) NOT NULL,
  ADDRESS    VARCHAR2(255 BYTE) NOT NULL,
  PHONE      VARCHAR2(255 BYTE) NOT NULL,
  EMAIL      VARCHAR2(255 BYTE) NOT NULL,
  USERNAME   VARCHAR2(255 BYTE) NOT NULL,
  PASSWORD   VARCHAR2(255 BYTE) NOT NULL,
  PRIMARY KEY (ID) USING INDEX TABLESPACE USERS STORAGE (INITIAL 64 K
                                                         NEXT 1 M
                                                         MAXEXTENTS UNLIMITED)
)
TABLESPACE USERS
STORAGE (INITIAL 64 K
         NEXT 1 M
         MAXEXTENTS UNLIMITED)
LOGGING;