DROP TABLE THETEAMPROJECT.BLOG CASCADE CONSTRAINTS;

CREATE TABLE THETEAMPROJECT.BLOG (
  ID          NUMBER(*, 0),
  TRADERID    VARCHAR2(255 BYTE),
  TITLE       VARCHAR2(255 BYTE),
  IMAGE       VARCHAR2(255 BYTE),
  DESCRIPTION VARCHAR2(1000 BYTE),
  PRIMARY KEY (ID) USING INDEX TABLESPACE USERS STORAGE (INITIAL 64 K
                                                         NEXT 1 M
                                                         MAXEXTENTS UNLIMITED)
)
TABLESPACE USERS
STORAGE (INITIAL 64 K
         NEXT 1 M
         MAXEXTENTS UNLIMITED)
LOGGING;