DROP TABLE THETEAMPROJECT.CATEGORY CASCADE CONSTRAINTS;

CREATE TABLE THETEAMPROJECT.CATEGORY (
  ID           NUMBER(*, 0),
  CATEGORYNAME VARCHAR2(255 BYTE) NOT NULL,
  GENDER       VARCHAR2(255 BYTE),
  PRIMARY KEY (ID) USING INDEX TABLESPACE USERS STORAGE (INITIAL 64 K
                                                         NEXT 1 M
                                                         MAXEXTENTS UNLIMITED)
)
TABLESPACE USERS
STORAGE (INITIAL 64 K
         NEXT 1 M
         MAXEXTENTS UNLIMITED)
LOGGING;