DROP TABLE THETEAMPROJECT.ORDERS CASCADE CONSTRAINTS;

CREATE TABLE THETEAMPROJECT.ORDERS (
  ID         NUMBER(*, 0),
  CUSTOMERID VARCHAR2(255 BYTE) NOT NULL,
  PRODUCTID  VARCHAR2(255 BYTE) NOT NULL,
  PAYDATE    VARCHAR2(255 BYTE) NOT NULL,
  STATUS     VARCHAR2(255 BYTE) NOT NULL,
  PRICE      VARCHAR2(255 BYTE) NOT NULL,
  SIZES      VARCHAR2(255 BYTE) NOT NULL,
  QUANTITY   VARCHAR2(255 BYTE) NOT NULL,
  TOTALPRICE VARCHAR2(255 BYTE) NOT NULL,
  TRADERID   NUMBER,
  TIMESLOT   VARCHAR2(128 BYTE),
  DAYSLOT    VARCHAR2(128 BYTE),
  PRIMARY KEY (ID) USING INDEX TABLESPACE USERS STORAGE (INITIAL 64 K
                                                         NEXT 1 M
                                                         MAXEXTENTS UNLIMITED)
)
TABLESPACE USERS
STORAGE (INITIAL 64 K
         NEXT 1 M
         MAXEXTENTS UNLIMITED)
LOGGING;