DROP TABLE THETEAMPROJECT.PRODUCT CASCADE CONSTRAINTS;

CREATE TABLE THETEAMPROJECT.PRODUCT (
  ID                 NUMBER(*, 0),
  PRODUCTNAME        VARCHAR2(255 BYTE) NOT NULL,
  PRODUCTDESCRIPTION VARCHAR2(255 BYTE) NOT NULL,
  IMAGE              VARCHAR2(255 BYTE),
  INSTOCK            VARCHAR2(255 BYTE) NOT NULL,
  PRICE              VARCHAR2(255 BYTE) NOT NULL,
  BRANDID            VARCHAR2(255 BYTE) NOT NULL,
  CATEGORYID         VARCHAR2(255 BYTE) NOT NULL,
  FEATURED           VARCHAR2(255 BYTE),
  SIZEAVAILABLE      VARCHAR2(255 BYTE) NOT NULL,
  TRADERSID          VARCHAR2(255 BYTE),
  SHOPID             VARCHAR2(255 BYTE),
  PRIMARY KEY (ID) USING INDEX TABLESPACE USERS STORAGE (INITIAL 64 K
                                                         NEXT 1 M
                                                         MAXEXTENTS UNLIMITED)
)
TABLESPACE USERS
STORAGE (INITIAL 64 K
         NEXT 1 M
         MAXEXTENTS UNLIMITED)
LOGGING;