DROP TABLE THETEAMPROJECT.SHOP CASCADE CONSTRAINTS;

CREATE TABLE THETEAMPROJECT.SHOP (
  ID         NUMBER(*, 0),
  TRADERID   VARCHAR2(255 BYTE) NOT NULL,
  SHOPNAME   VARCHAR2(255 BYTE) NOT NULL,
  LOCATION   VARCHAR2(255 BYTE) NOT NULL,
  PERMISSION VARCHAR2(255 BYTE) NOT NULL,
  PRIMARY KEY (ID) USING INDEX TABLESPACE USERS STORAGE (INITIAL 64 K
                                                         NEXT 1 M
                                                         MAXEXTENTS UNLIMITED)
)
TABLESPACE USERS
STORAGE (INITIAL 64 K
         NEXT 1 M
         MAXEXTENTS UNLIMITED)
LOGGING;